experiment_config:
  output_dir: _results/listOps/prob/hosvd
  num_run: 3
  metric_class_list:
    - exputils.metrics.Accuracy
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.listOps.task_utils.ListOpsLoader
  params:
    data_dir:  data/listOps/dgl/
    only_root: False
    batch_size: 50
  max_tr_elements: 20000
trainer_config:
  class: exputils.trainerss.EMTrainer
  params:
    early_stopping_patience: 50
    n_epochs: 200
    evaluate_on_training_set: False
    eps_loss: 0.001
exp_module_config:
  class: models.prob.recursive.HRM
  params:
    h_size: [50, 100, 150]
    only_root_state: False
    state_transition_config:
      class: models.prob.state_transition.Hosvd
      params:
        num_types: 4
        pos_stationarity: False
        max_output_degree: 5
        rank: [2,3,5]
    x_emission_config:
      class: thlogprob.distributions.Categorical
      params:
        num_labels: 10
    y_emission_config:
      class: thlogprob.distributions.Categorical
      params:
        num_labels: 10