dataset_config:
  data_dir: data/sick/dgl_tree_net
  output_type: entailment
experiment_config:
  metric_class_list:
  - exputils.metrics.Accuracy
  num_run: 3
  output_dir: results/sick_e/no_types/tree_net/
training_config:
  class: exputils.trainerss.NeuralTrainer
  params:
    batch_size: 25
    collate_fun:
      class: torch.nn.CrossEntropyLoss
      params: entailment
    early_stopping_patience: 5
    evaluate_on_training_set: true
    loss_function:
      class: torch.nn.CrossEntropyLoss
    n_epochs: 100
    optimiser:
      class: torch.optim.Adam
      params:
        'lr': [0.001,0.005,0.008]
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    cell_module_config:
      class: models.neural.cells.TreeNet
      params:
        aggregator_class: models.neural.aggregators.SumChild
        max_output_degree: 2
        pos_stationarity: false
    h_size:
    - 150
    - 200
    - 300
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: pretrained
        freeze: true
        pretrained_embs: data/sick/dgl_tree_net/pretrained_embs.pkl
    only_root_state: true
    output_module_config:
      class: tasks.sick.exp_utils.EntailmentClassifier
      params:
        h_size:
        - 50
        - 100
        - 200
        out_size: 5
