experiment_config:
  metric_class_list:
  - exputils.metrics.Accuracy
  num_run: 3
  output_dir: _results/trec_6/no_types/bin_const/hosvd
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.sst.task_utils.SstLoader
  params:
    data_dir: data/trec/dgl_bin_const
    output_type: coarse
    batch_size:
      - 10
      - 25
      - 40
training_config:
  class: exputils.trainerss.NeuralTrainer
  params:
    early_stopping_patience: 5
    evaluate_on_training_set: true
    loss_function:
      class: torch.nn.CrossEntropyLoss
    n_epochs: 100
    optimiser:
      class: torch.optim.Adadelta
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    cell_module_config:
      class: models.neural.cells.LSTM
      params:
        aggregator_class: models.neural.aggregators.Hosvd
        max_output_degree: 2
        pos_stationarity: false
        rank:
        - 10
        - 20
        - 50
    h_size:
    - 150
    - 200
    - 300
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: pretrained
        freeze: true
        pretrained_embs: data/trec/dgl_bin_const/pretrained_embs.pkl
    only_root_state: true
    output_module_config:
      class: models.neural.others.MLP
      params:
        dropout: 0.5
        h_size:
        - 0
        - 50
        - 100
