experiment_config:
  output_dir: _results/sst_5_with_leaf/no_types/const/tt
  num_run: 3
  metric_class_list:
    - exputils.metrics.RootAccuracy
    - exputils.metrics.Accuracy
    - exputils.metrics.LeavesAccuracy
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.sst.exp_utils.SstLoader
  params:
    data_dir: data/sst/dgl_const
    batch_size:
      - 5
      - 10
      - 25
trainer_config:
  class: exputils.trainerss.NeuralTrainer
  params:
    early_stopping_patience: 5
    n_epochs: 100
    evaluate_on_training_set: False
    optimiser:
      class: torch.optim.Adadelta
    loss_function:
      class: torch.nn.CrossEntropyLoss
      params:
        ignore_index: -1
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    h_size: [150, 200, 300]
    only_root_state: False
    cell_module_config:
      class: models.neural.cells.LSTM
      params:
        aggregator_class: models.neural.aggregators.TensorTrain
        pos_stationarity: True
        rank: [10, 30]
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: pretrained
        pretrained_embs: data/sst/dgl_const/pretrained_embs.pkl
        freeze: False
    output_module_config:
      class: models.neural.others.MLP
      params:
        out_size: 5
        h_size: [0, 500, 1000]
        dropout: 0.5