
experiment_config:
  metric_class_list:
  - exputils.metrics.Accuracy
  num_run: 3
  output_dir: _results/boolSent/boolSent_2/HRM/full
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.boolSent.task_utils.BoolSentLoader
  params:
    data_dir:  data/boolSent/dgl/boolSent_2
    only_root: False
    batch_size: 50
trainer_config:
  class: exputils.trainers.EMTrainer
  params:
    params:
      batch_size: 100
      early_stopping_patience: 50
      eps_loss: 0.1
      evaluate_on_training_set: Fale
      n_epochs: 500
exp_module_config:
  class: models.prob.recursive.HRM
  params:
    h_size:
    - 2
    - 3
    - 5
    only_root_state: false
    state_transition_config:
      class: models.prob.state_transition.Full
      params:
        max_output_degree: 2
        num_types: 4
        pos_stationarity: false
x_emission_config:
      class: thlogprob.distributions.Categorical
      params:
        num_labels: 2
        num_vars: 1
    y_emission_config:
      class: thlogprob.distributions.Categorical
      params:
        num_labels: 2
        num_vars: 1
