experiment_config:
  output_dir: results/listOps/prob/canonical
  num_run: 3
  metric_class_list:
    - exputils.metrics.Accuracy
dataset_config:
  #dataset_class: experiments.sst.sst_dataset.SSTBinaryDataset
  # this folder must contains: train.pkl, dev.pkl, test.pkl
  data_dir: data/listOps/dgl/
  max_tr_elements: 10000
others_config:
  gpu: -1
trainer_config:
  class: exputils.trainerss.EMTrainer
  training_params:
    batch_size: 50
    early_stopping_patience: 50
    n_epochs: 200
    evaluate_on_training_set: False
    eps_loss: 0.001
    collate_fun:
      class: tasks.listOps.exp_utils.ListOpsCollateFun
      params:
        only_root: False
exp_module_config:
  class: models.prob.recursive.HRM
  params:
    h_size: [20, 50, 100]
    only_root_state: False
    state_transition_config:
      class: models.prob.state_transition.Canonical
      params:
        num_types: 4
        pos_stationarity: False
        max_output_degree: 5
        rank: [20, 50, 100]
    x_emission_config:
      class: thlogprob.distributions.Categorical
      params:
        num_labels: 10
    y_emission_config:
      class: thlogprob.distributions.Categorical
      params:
        num_labels: 10