experiment_config:
  metric_class_list:
  - exputils.metrics.Accuracy
  num_run: 3
  output_dir: _results/boolSent/boolSent_5/HRM/sp
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.boolSent.exp_utils.BoolSentLoader
  params:
    data_dir:  data/boolSent/dgl/boolSent_5
    only_root: False
    batch_size: 50
trainer_config:
  class: exputils.trainers.EMTrainer
  params:
    early_stopping_patience: 50
    eps_loss: 0.001
    evaluate_on_training_set: false
    n_epochs: 200
exp_module_config:
  class: models.prob.recursive.HRM
  params:
    h_size:
    - 5
    - 10
    - 20
    - 50
    only_root_state: false
    state_transition_config:
      class: models.prob.state_transition.SwitchingParent
      params:
        max_output_degree: 5
        num_types: 4
        pos_stationarity: false
    x_emission_config:
      class: thlogprob.distributions.Categorical
      params:
        num_labels: 2
    y_emission_config:
      class: thlogprob.distributions.Categorical
      params:
        num_labels: 2
