experiment_config:
  #experiment_class: tasks.toy.run_utils.NeuralToyExperiment
  output_dir: _results/listOps/RNN/tt
  num_run: 3
  metric_class_list:
    - exputils.metrics.Accuracy
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.listOps.task_utils.ListOpsLoader
  params:
    data_dir:  data/listOps/dgl/
    only_root: True
    batch_size: 50
trainer_config:
  class: exputils.trainerss.NeuralTrainer
  params:
    early_stopping_patience: 10
    n_epochs: 100
    evaluate_on_training_set: False
    optimiser:
      class: torch.optim.Adadelta
    loss_function:
      class: torch.nn.CrossEntropyLoss
      params:
        ignore_index: -1
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    h_size: 50
    only_root_state: True
    cell_module_config:
      class: models.neural.cells.Typed
      params:
        num_types: 4
        cell_config:
          class: models.neural.cells.RNN
          params:
            aggregator_class: models.neural.aggregators.TensorTrain #
            pos_stationarity: False
            max_output_degree: 5
            rank: [4, 12, 32]
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: one_hot
        num_embs: 10
    output_module_config:
      class: models.neural.others.MLP
      params:
        out_size: 10
        num_layers: 2
        h_size: 20