experiment_config:
  metric_class_list:
  - exputils.metrics.Accuracy
  num_run: 3
  output_dir: _results/sick_e/no_types/const/tt
  seed: -1
  device: 'cpu'
dataset_config:
  class: tasks.sick.task_utils.SickLoader
    params:
      data_dir: data/sick/dgl_const
      output_type: entailment
      batch_size:
        - 25
        - 40
training_config:
  class: exputils.trainerss.NeuralTrainer
  params:
    early_stopping_patience: 5
    evaluate_on_training_set: true
    loss_function:
      class: torch.nn.CrossEntropyLoss
    n_epochs: 100
    optimiser:
      class: torch.optim.Adadelta
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    cell_module_config:
      class: models.neural.cells.LSTM
      params:
        aggregator_class: models.neural.aggregators.TensorTrain
        max_output_degree: 2
        pos_stationarity: true
        rank:
        - 10
        - 30
    h_size:
    - 150
    - 200
    - 300
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: pretrained
        freeze: true
        pretrained_embs: data/sick/dgl_const/pretrained_embs.pkl
    only_root_state: true
    output_module_config:
      class: tasks.sick.task_utils.EntailmentClassifier
      params:
        h_size:
        - 50
        - 100
        - 200
        out_size: 5
