experiment_config:
  #experiment_class: tasks.toy.run_utils.NeuralToyExperiment
  output_dir: _results/boolSent/boolSent_2/RNN/sumchild
  num_run: 3
  metric_class_list:
    - exputils.metrics.Accuracy
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.boolSent.exp_utils.BoolSentLoader
  params:
    data_dir:  data/boolSent/dgl/boolSent_2
    only_root: True
    batch_size: 50
trainer_config:
  class: exputils.trainers.NeuralTrainer
  training_params:
    early_stopping_patience: 5
    n_epochs: 100
    evaluate_on_training_set: False
    optimiser:
      class: torch.optim.Adadelta
    loss_function:
      class: torch.nn.CrossEntropyLoss
      params:
        ignore_index: -1
    collate_fun:
      class: tasks.boolSent.exp_utils.BoolSentCollateFun
      params:
        only_root: True
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    h_size: [10, 20, 50, 100, 300]
    only_root_state: True
    cell_module_config:
      class: models.neural.cells.Typed
      params:
        num_types: 4
        cell_config:
          class: models.neural.cells.RNN
          params:
            aggregator_class: models.neural.aggregators.SumChild #
            pos_stationarity: False
            max_output_degree: 2
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: one_hot
        num_embs: 2
    output_module_config:
      class: models.neural.others.MLP
      params:
        out_size: 2
        num_layers: 0