dataset_config:
  data_dir: data/boolSent/dgl/boolSent_3/
experiment_config:
  metric_class_list:
  - exputils.metrics.Accuracy
  num_run: 3
  output_dir: results/boolSent/boolSent_3/HRM/sp
others_config:
  gpu: -1
trainer_config:
  class: exputils.trainer.EMTrainer
  params:
    batch_size: 50
    collate_fun:
      class: tasks.boolSent.exp_utils.BoolSentCollateFun
      params:
        only_root: false
    early_stopping_patience: 50
    eps_loss: 0.001
    evaluate_on_training_set: false
    n_epochs: 200
tree_module_config:
  class: models.prob.recursive.HRM
  params:
    h_size:
    - 5
    - 10
    - 20
    - 50
    only_root_state: false
    state_transition_config:
      class: models.prob.state_transition.SwitchingParent
      params:
        max_output_degree: 3
        num_types: 4
        pos_stationarity: false
    x_emission_config:
      class: models.prob.distribution.Categorical
      params:
        num_labels: 2
    y_emission_config:
      class: models.prob.distribution.Categorical
      params:
        num_labels: 2
