experiment_config:
  output_dir: _results/trec_6/no_types/const/tt
  num_run: 3
  metric_class_list:
    - exputils.metrics.Accuracy
dataset_config:
  #dataset_class: experiments.sst.sst_dataset.SSTBinaryDataset
  # this folder must contains: train.pkl, dev.pkl, test.pkl
  data_dir: data/trec/dgl_const
others_config:
  #seed: 1949013946
  gpu: -1
trainer_config:
  class: exputils.trainerss.NeuralTrainer
  params:
    batch_size: [25, 40] #[10, 25, 40]
    early_stopping_patience: 10
    n_epochs: 100
    evaluate_on_training_set: False
    optimiser:
      class: torch.optim.Adadelta
    loss_function:
      class: torch.nn.CrossEntropyLoss
    collate_fun:
      class: tasks.trec.exp_utils.TrecCollateFun
      params:
        output_type: coarse
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    h_size: [150, 200, 300]
    only_root_state: True
    cell_module_config:
      class: models.neural.cells.LSTM
      params:
        aggregator_class: models.neural.aggregators.TensorTrain #Canonical
        pos_stationarity: True
        rank: [10, 30]
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: pretrained
        pretrained_embs: data/trec/dgl_const/pretrained_embs.pkl
        freeze: True
    output_module_config:
      class: models.neural.others.MLP
      params:
        out_size: 6
        h_size: [0, 50, 100]
