experiment_config:
  output_dir: _results/trec_6/no_types/const/tt
  num_run: 3
  metric_class_list:
    - exputils.metrics.Accuracy
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.sst.task_utils.SstLoader
  params:
    data_dir: data/trec/dgl_const
    output_type: coarse
    batch_size:
      - 10
      - 25
      - 40
trainer_config:
  class: exputils.trainerss.NeuralTrainer
  params:
    early_stopping_patience: 5
    n_epochs: 100
    evaluate_on_training_set: False
    optimiser:
      class: torch.optim.Adadelta
    loss_function:
      class: torch.nn.CrossEntropyLoss
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    h_size: [150, 200, 300]
    only_root_state: True
    cell_module_config:
      class: models.neural.cells.LSTM
      params:
        aggregator_class: models.neural.aggregators.TensorTrain #Canonical
        pos_stationarity: True
        rank: [10, 30]
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: pretrained
        pretrained_embs: data/trec/dgl_const/pretrained_embs.pkl
        freeze: True
    output_module_config:
      class: models.neural.others.MLP
      params:
        out_size: 6
        h_size: [0, 50, 100]
