experiment_config:
  metric_class_list:
  - tasks.sick.run_utils.PearsonSICK
  - tasks.sick.run_utils.MseSICK
  num_run: 3
  output_dir: _results/sick_r/no_types/tree_net/
  device: 'cpu'
  seed: -1
dataset_config:
  class: tasks.sick.task_utils.SickLoader
  params:
    data_dir: data/sick/dgl_tree_net
    output_type: relatedness
    batch_size: 25
training_config:
  class: exputils.trainerss.NeuralTrainer
  params:
    early_stopping_patience: 5
    evaluate_on_training_set: true
    loss_function:
      class: tasks.sick.task_utils.SickRelatednessLoss
    n_epochs: 100
    optimiser:
      class: torch.optim.Adam
      params:
        'lr': [0.001,0.005,0.008]
exp_module_config:
  class: models.neural.recursive.RecNN
  params:
    cell_module_config:
      class: models.neural.cells.TreeNet
      params:
        aggregator_class: models.neural.aggregators.SumChild
        max_output_degree: 2
        pos_stationarity: false
    h_size:
    - 150
    - 200
    - 300
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: pretrained
        freeze: true
        pretrained_embs: data/sick/dgl_tree_net/pretrained_embs.pkl
    only_root_state: true
    output_module_config:
      class: tasks.sick.task_utils.RelatednessClassifier
      params:
        h_size:
        - 50
        - 100
        - 200
        out_size: 5
