experiment_config:
  #experiment_class: tasks.toy.run_utils.NeuralToyExperiment
  output_dir: results/listOps/LSTM/tt
  num_run: 3
  metric_class_list:
    - exputils.metrics.Accuracy
dataset_config:
  #dataset_class: experiments.sst.sst_dataset.SSTBinaryDataset
  # this folder must contains: train.pkl, dev.pkl, test.pkl
  data_dir: data/listOps/dgl/
others_config:
  gpu: -1
trainer_config:
  class: exputils.trainers.NeuralTrainer
  training_params:
    batch_size: 50
    early_stopping_patience: 5
    n_epochs: 100
    evaluate_on_training_set: False
    optimiser:
      class: torch.optim.Adadelta
    loss_function:
      class: torch.nn.CrossEntropyLoss
      params:
        ignore_index: -1
    collate_fun:
      class: tasks.listOps.exp_utils.ListOpsCollateFun
      params:
        only_root: True
tree_module_config:
  class: models.neural.recursive.RecNN
  params:
    h_size: 50
    only_root_state: True
    cell_module_config:
      class: models.neural.cells.Typed
      params:
        num_types: 4
        cell_config:
          class: models.neural.cells.LSTM
          params:
            aggregator_class: models.neural.aggregators.TensorTrain #
            pos_stationarity: False
            max_output_degree: 5
            rank: [4, 12, 32]
    input_module_config:
      class: models.neural.others.VectorEmbedding
      params:
        embedding_type: one_hot
        num_embs: 10
    output_module_config:
      class: models.neural.others.MLP
      params:
        num_classes: 10
        num_layers: 2
        h_size: 20